name: add-build-number

on: push

env:
  CURL_OPTIONS: "--fail-with-body --location --show-error --silent"

defaults:
  run:
    shell: bash

jobs:
  set-build-number:
    uses: polarlabs/factory/.github/workflows/set-build-number.yml@main

  add-build-number:
    runs-on: ubuntu-latest
    needs: [set-build-number]

    steps:
      - name: create tag object
        env:
          BUILD_NUMBER: ${{ needs.set-build-number.outputs.BUILD_NUMBER }}
        run: |
             curl ${{ env.CURL_OPTIONS }} \
             -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             ${{ github.api_url }}/repos/${{ github.repository }}/git/tags \
             --data '{ "tag": "build/${{ env.BUILD_NUMBER }}", 
                       "message": "auto incremented build number", 
                       "object": "${{ github.sha }}", 
                       "type": "commit" }'

      - name: create ref
        env:
          BUILD_NUMBER: ${{ needs.set-build-number.outputs.build_number }}
        run: |
             curl ${{ env.CURL_OPTIONS }} \
             -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             ${{ github.api_url }}/repos/${{ github.repository }}/git/refs \
             --data '{ "ref": "refs/tags/build/${{ env.BUILD_NUMBER }}", 
                       "sha": "${{ github.sha }}" }'
