name: add-build-number

on: push

env:
  CURL_OPTIONS: "--fail-with-body --location --show-error --silent"

defaults:
  run:
    shell: bash

jobs:
  tag-ref-as-build:
    uses: polarlabs/factory/.github/workflows/tag-ref-as-build.yml@v/1.0.0
