name: create version

on:
  create:
    branches:
      - main
    tags:
      - v/*.*.*

defaults:
  run:
    shell: bash

jobs:
  tag-ref-as-build:
    uses: polarlabs/factory/.github/workflows/tag-ref-as-build.yml@v/1.0.0

  set-version-string:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: |
             echo "VERSION_STRING=${GITHUB_REF_NAME}" >> $GITHUB_ENV

  echo-env-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Version string
        run: |
          echo "Version: $VERSION_STRING"

      - name: Echo Build number
        run: |
          echo "Build: $BUILD_NUMBER"
