name: create version

on:
  create:
    branches:
      - main
    tags:
      - v/*.*.*

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: |
             echo "VERSION_STRING=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Echo Version string
        run: |
          echo "Version: $VERSION_STRING"
