name: create version

on:
  create:
    branches:
      - main
    tags:
      - v/*.*.*

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: |
             echo "Triggered"
